### ISSUE TITLE
Build Error with Next 15

### ISSUE THREAD

**Issue by amirsio** [workos/authkit-nextjs#127] opened 2024-11-01 20:08 UTC
**Describe the bug**
Production build fails due to 'use server' being used in impersonation.tsx, which is a client component. A log of the following can seen below:

```
web:build: Failed to compile.
web:build:
web:build: ../../node_modules/.pnpm/@workos-inc+authkit-nextjs@0.13.1_next@15.0.2_@opentelemetry+api@1.9.0_@playwright+test@1.48._q3zgskv7sacnwxmjbpuilruaq4/node_modules/@workos-inc/authkit-nextjs/dist/esm/impersonation.js
web:build: Error:   × It is not allowed to define inline "use server" annotated Server Actions in Client Components.
web:build:   │ To use Server Actions in a Client Component, you can either export them from a separate file with "use server" at the top, or pass them down through props from a Server Component.
web:build:   │
web:build:   │ Read more: https://nextjs.org/docs/app/api-reference/functions/server-actions#with-client-components
web:build:   │
web:build:     ╭─[/Users/asadv/realer/node_modules/.pnpm/@workos-inc+authkit-nextjs@0.13.1_next@15.0.2_@opentelemetry+api@1.9.0_@playwright+test@1.48._q3zgskv7sacnwxmjbpuilruaq4/node_modules/@workos-inc/authkit-nextjs/dist/esm/impersonation.js:50:1]
web:build:  47 │                 lineHeight: '1.4',
web:build:  48 │             } },
web:build:  49 │             React.createElement("form", { action: async () => {
web:build:  50 │                     'use server';
web:build:     ·                     ────────────
web:build:  51 │                     await signOut();
web:build:  52 │                 }, style: {
web:build:  53 │                     display: 'flex',
web:build:     ╰────
web:build:
web:build: Import trace for requested module:
web:build: ../../node_modules/.pnpm/@workos-inc+authkit-nextjs@0.13.1_next@15.0.2_@opentelemetry+api@1.9.0_@playwright+test@1.48._q3zgskv7sacnwxmjbpuilruaq4/node_modules/@workos-inc/authkit-nextjs/dist/esm/impersonation.js
web:build: ../../node_modules/.pnpm/@workos-inc+authkit-nextjs@0.13.1_next@15.0.2_@opentelemetry+api@1.9.0_@playwright+test@1.48._q3zgskv7sacnwxmjbpuilruaq4/node_modules/@workos-inc/authkit-nextjs/dist/esm/index.js
web:build: ./components/root-providers.tsx
web:build:
web:build:
web:build: > Build failed because of webpack errors
web:build:  ELIFECYCLE  Command failed with exit code 1.
web:build:  ELIFECYCLE  Command failed with exit code 1.
web:build: ERROR: command finished with error: command (/Users/asadv/realer/apps/web) /Users/asadv/realer/node_modules/.bin/pnpm run build exited (1)
web#build: command (/Users/asadv/realer/apps/web) /Users/asadv/realer/node_modules/.bin/pnpm run build exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    10.986s
Failed:    web#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

**To Reproduce**
Run `pnpm build` when using workos auth.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: MacOS
 - authkit-nextjs version: 0.13.1
 - Next.js version: 15.0.2

**Comment by PaulAsjes** [comment] 2024-11-04 09:37
This is a duplicate of https://github.com/workos/authkit-nextjs/issues/80 so I'm closing this for now. Will be looking further into this soon.

**Closed by PaulAsjes** 2024-11-04 09:37 UTC
