### ISSUE TITLE
[Feature request]: Be able to configure `WORKOS_REDIRECT_URI` as a parameter

### ISSUE THREAD

**Issue by wuweiweiwu** [workos/authkit-nextjs#78] opened 2024-08-17 00:55 UTC
we use vercel for our preview deployments and since `WORKOS_REDIRECT_URI` is loaded as an environment variable it makes it very difficult for us to substitute that value in since each deploy preview has a unique URL

**Comment by PaulAsjes** [comment] 2024-08-19 09:26
Thanks for the report! I'm closing this as it's a functional duplicate of https://github.com/workos/authkit-nextjs/issues/45 but rest assured that we're working on it.

**Closed by PaulAsjes** 2024-08-19 09:26 UTC
Labels: enhancement
