### ISSUE TITLE
It is not allowed to define inline "use server" annotated Server Actions in Client Components.

### ISSUE THREAD

**Issue by moroshko** [workos/authkit-nextjs#84] opened 2024-09-11 02:50 UTC
When `AuthKitProvider` is used directly in the layout, it works fine:

**`layout.tsx`**
```tsx
import type { PropsWithChildren } from "react";
import { AuthKitProvider } from "@workos-inc/authkit-nextjs";

const SignedInLayout = ({ children }: PropsWithChildren) => {
  return (
    <AuthKitProvider>
      <main>{children}</main>
    </AuthKitProvider>
  );
};

export default SignedInLayout;
```

However, if it's used inside a custom `Providers` client component, it produces an error:

**`layout.tsx`**
```tsx
import type { PropsWithChildren } from "react";
import { Providers } from "./components/Providers/Providers";

const SignedInLayout = ({ children }: PropsWithChildren) => {
  return (
    <Providers>
      <main>{children}</main>
    </Providers>
  );
};

export default SignedInLayout;
```

**`Providers.tsx`**
```tsx
"use client";

import { AuthKitProvider } from "@workos-inc/authkit-nextjs";
import type { PropsWithChildren } from "react";

const Providers = ({ children }: PropsWithChildren) => {
  return <AuthKitProvider>{children}</AuthKitProvider>;
};

export { Providers };
```

![CleanShot 2024-09-11 at 12 46 51@2x](https://github.com/user-attachments/assets/2c89494c-56c8-4905-a870-b8c5ff075f75)

Removing `"use client"` from `Providers.tsx` solves the issue, but this solution won't work if I have other third-party providers that don't have their own `"use client"` or if I want to add an `onSessionExpired` prop to `AuthKitProvider`.

Any ideas?

I'm using `@workos-inc/authkit-nextjs@0.10.0`

**Comment by PaulAsjes** [comment] 2024-09-11 07:22
Thanks for the report and the detailed reproduction steps! This is a duplicate of https://github.com/workos/authkit-nextjs/issues/80 so I'm closing this, but we're looking into fixing this.

**Closed by PaulAsjes** 2024-09-11 07:22 UTC
Labels: bug
